_mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    # Adicionando as urls `accounts` que o Django já tem prontas.
    # Templates pode ser modificados em `templates/registration`.
    path('accounts/', include('django.contrib.auth.urls')),
    # Rest
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Aplicativos.
    path('', include('home.urls')),
    path('axios/', include('axios.urls')),
    path('blog/', include('blog.urls')),
    path('gitignore/', include('gitignore.urls')),
    path('jquery/', include('jquery.urls')),
    path('jsfetch/', include('jsfetch.urls')),
    path('jsxmlhttprequest/', include('jsxmlhttprequest.urls')),
    path('leafletjs/', include('leafletjs.urls')),
    path('note/', include('note.urls')),
    path('poll/', include('poll.urls')),
    path('upload/', include('upload.urls')),
    # Configurando arquivos de media, não fazer isso em produção!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axios/urls.py
from django.urls import path

from .views import axios_get, axios_post, index

app_name = 'axios'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='get/', view=axios_get, name='get'),
    path(route='post/', view=axios_post, name='post'),
]

blog/urls.py
from django.urls import path

from .views import index, post_detail, post_new, post_edit, post_delete, post_drafts

app_name = 'blog'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='post/drafts/', view=post_drafts, name='post_drafts'),
    path(route='post/<int:pk>/', view=post_detail, name='post_detail'),
    path(route='post/new/', view=post_new, name='post_new'),
    path(route='post/<int:pk>/edit/', view=post_edit, name='post_edit'),
    path(route='post/<int:pk>/delete/', view=post_delete, name='post_delete'),
]

home/urls.py
from django.urls import path

from .views import index

app_name = 'home'
urlpatterns = [
    path(route='', view=index, name='index'),
]

note/urls.py
from django.urls import path

from .views import NoteIndex, NoteCreate, NoteUpdate, NoteDelete

app_name = 'note'
urlpatterns = [
    path(route='', view=NoteIndex.as_view(), name='index'),
    path(route='new/', view=NoteCreate.as_view(), name='create'),
    path(route='<int:pk>/update/', view=NoteUpdate.as_view(), name='update'),
    path(route='<int:pk>/delete/', view=NoteDelete.as_view(), name='delete'),
]

poll/urls.py
from django.urls import path

from . import views

app_name = 'poll'
urlpatterns = [
    path(route='', view=views.IndexView.as_view(), name='index'),
    path(route='<int:pk>/', view=views.DetailView.as_view(), name='detail'),
    path(route='<int:pk>/results/', view=views.ResultsView.as_view(), name='results'),
    path(route='<int:question_id>/vote/', view=views.vote, name='vote'),
]

templates/base/base-bulma.html
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    {% load static %}
    <link href="{% static 'favicon/favicon.ico' %}" rel="shortcut icon">
    <link href="{% static 'favicon/favicon.png' %}" rel="icon" type="image/png">
    <link href="{% static 'favicon/favicon.svg' %}" rel="icon" type="image/svg+xml">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <title>{% block title %}Python for Devs{% endblock title %}</title>
    {% block seo %}
    <meta content="Django, Python, Python 3, Ajax, VueJs" name="keywords">
    <meta content="Renato dos Santos Cruz" name="author">
    {% endblock seo %}
    {% block css %}
    <link href="{% static 'base/css/bulma-0.8.0/bulma.min.css' %}" rel="stylesheet">
    {% endblock css %}
</head>

<body>
<div class="container">
    {% include "base/navbar.html" %}
    {% block content %}{% endblock content %}
    {% include "base/footer.html" %}
</div>
{% block scripts %}
<script charset="utf-8" src="{% static 'base/js/toggle-navbar.js' %}"></script>
{% endblock scripts %}
</body>

</html>

templates/base/footer.html
<footer class="footer">
    <div class="content has-text-centered">
        <p>
            <strong>Python for Devs</strong> criado por <a href="https://www.linkedin.com/in/natorsc/">Renato Cruz</a>.
            2019 -
            {% now "Y" %}
        </p>
    </div>
</footer>

templates/base/navbar-logged.html
<div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link">Logado com: {{ user }}</a>
    <div class="navbar-dropdown">
        <a class="navbar-item" href="#">Configuração</a>
        <hr class="navbar-divider">
        <a class="navbar-item" href="#">Conta</a>
        <hr class="navbar-divider">
        <a class="navbar-item" href="{% url 'logout' %}">Sair</a>
    </div>
</div>

templates/base/navbar.html
<nav aria-label="main navigation" class="navbar" role="navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home:index' %}">Home</a>
        <a aria-expanded="false" aria-label="menu" class="navbar-burger burger" data-target="NavbarBurger"
           role="button">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div class="navbar-menu" id="NavbarBurger">
        <div class="navbar-start">
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Ajax</a>
                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'axios:index' %}">Axios</a>
                    <a class="navbar-item" href="{% url 'jquery:index' %}">jQuery</a>
                    <a class="navbar-item" href="{% url 'jsfetch:index' %}">Fetch</a>
                    <a class="navbar-item" href="{% url 'jsxmlhttprequest:index' %}">XMLHttpRequest</a>
                </div>
            </div>
            <a class="navbar-item" href="{% url 'blog:index' %}">Blog</a>
            <a class="navbar-item" href="{% url 'poll:index' %}">Enquete</a>
            <a class="navbar-item" href="{% url 'leafletjs:index' %}">Geolocalização</a>
            <a class="navbar-item" href="{% url 'note:index' %}">Notas</a>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="{% url 'upload:index' %}">Upload</a>
                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'upload:file' %}">Arquivo</a>
                    <a class="navbar-item" href="{% url 'upload:files' %}">Arquivos</a>
                    <a class="navbar-item" href="#">Imagem</a>

                </div>
            </div>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                {% if user.is_authenticated %}
                {% include 'base/navbar-logged.html' %}
                {% else %}
                <div class="buttons">
                    <a class="button is-primary" disabled><strong>Sign up</strong></a>
                    <a class="button is-light" href="{% url 'login' %}">Log in</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>