_mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    # Adicionando as urls `accounts` que o Django já tem prontas.
    # Templates pode ser modificados em `templates/registration`.
    path('accounts/', include('django.contrib.auth.urls')),
    # Rest
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Aplicativos.
    path('', include('home.urls')),
    path('axios/', include('axios.urls')),
    path('blog/', include('blog.urls')),
    path('gitignore/', include('gitignore.urls')),
    path('jquery/', include('jquery.urls')),
    path('jsfetch/', include('jsfetch.urls')),
    path('jsxmlhttprequest/', include('jsxmlhttprequest.urls')),
    path('leafletjs/', include('leafletjs.urls')),
    path('note/', include('note.urls')),
    path('poll/', include('poll.urls')),
    path('upload/', include('upload.urls')),
    # Configurando arquivos de media, não fazer isso em produção!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import index, post_detail, post_new, post_edit, post_delete, post_drafts

app_name = 'blog'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='post/drafts/', view=post_drafts, name='post_drafts'),
    path(route='post/<int:pk>/', view=post_detail, name='post_detail'),
    path(route='post/new/', view=post_new, name='post_new'),
    path(route='post/<int:pk>/edit/', view=post_edit, name='post_edit'),
    path(route='post/<int:pk>/delete/', view=post_delete, name='post_delete'),
]

jsfetch/urls.py
from django.urls import path

from .views import js_fetch_get, js_fetch_post, index

app_name = 'jsfetch'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='get/', view=js_fetch_get, name='get'),
    path(route='post/', view=js_fetch_post, name='post'),
]

jsfetch/models.py
from django.db import models

# Create your models here.

axios/forms.py
from django import forms


class AxiosForm(forms.Form):
    first_name = forms.CharField(
        label='Nome',
        max_length=10,
        help_text='Tamanho maximo de 10 caracteres',
        widget=forms.TextInput(attrs={'class': 'input'}),
    )

    last_name = forms.CharField(
        label='Sobrenome',
        max_length=30,
        help_text='Tamanho maximo de 30 caracteres',
        widget=forms.TextInput(attrs={'class': 'input'}),
    )

jsfetch/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST


def index(request):
    return render(
        request=request,
        template_name='jsfetch/index.html',
    )


@require_GET
def js_fetch_get(request):
    first_name = request.GET.get('first_name', None)
    last_name = request.GET.get('last_name', None)
    return JsonResponse(
        data={
            'first_name': first_name,
            'last_name': last_name,
            'info': 'Os dados foram obtidos via JS fetch GET',
        },
        status=200,
    )


@require_POST
def js_fetch_post(request):
    first_name = request.POST.get('first_name', None)
    last_name = request.POST.get('last_name', None)
    return JsonResponse(
        data={
            'first_name': first_name,
            'last_name': last_name,
            'info': 'Os dados foram obtidos via JS fetch POST',
        },
        status=200,
    )

jsfetch/templates/jsfetch/index.html
{% extends 'base/base-bulma.html' %}
{% block title %}Ajax com JS fetch{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Realizando requisições Ajax com JS fetch e Django" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Ajax com JS fetch</h1>
        <form id="form">
            {% csrf_token %}
            <div class="field">
                <label class="label">Nome</label>
                <div class="control">
                    <input class="input" id="id_first_name" name="first_name" placeholder="Nome" type="text">
                </div>
                <p class="help">Tamanho maximo de 10 caracteres</p>
            </div>
            <div class="field">
                <label class="label">Sobrenome</label>
                <div class="control">
                    <input class="input" id="id_last_name" name="last_name" placeholder="Sobrenome" type="text">
                </div>
                <p class="help">Tamanho maximo de 30 caracteres</p>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <a class="button is-primary" onclick="jsfetch_get_data()">Via GET</a>
                </div>
                <div class="control">
                    <a class="button is-primary" onclick="jsfetch_post_data()">Via POST</a>
                </div>
            </div>
        </form>
        <br>
        <p class="has-text-centered	has-text-link" id="result">...</p>
    </div>
</section>
{% endblock content %}
{% block scripts %}
{{ block.super }}
{% load static %}
<script charset="utf-8" src="{% static 'jsfetch/js/jsfetch-get.js' %}"></script>
<script charset="utf-8" src="{% static 'jsfetch/js/jsfetch-post.js' %}"></script>
{% endblock scripts %}