_mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    # Adicionando as urls `accounts` que o Django já tem prontas.
    # Templates pode ser modificados em `templates/registration`.
    path('accounts/', include('django.contrib.auth.urls')),
    # Rest
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Aplicativos.
    path('', include('home.urls')),
    path('axios/', include('axios.urls')),
    path('blog/', include('blog.urls')),
    path('gitignore/', include('gitignore.urls')),
    path('jquery/', include('jquery.urls')),
    path('jsfetch/', include('jsfetch.urls')),
    path('jsxmlhttprequest/', include('jsxmlhttprequest.urls')),
    path('leafletjs/', include('leafletjs.urls')),
    path('note/', include('note.urls')),
    path('poll/', include('poll.urls')),
    path('upload/', include('upload.urls')),
    # Configurando arquivos de media, não fazer isso em produção!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import index, post_detail, post_new, post_edit, post_delete, post_drafts

app_name = 'blog'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='post/drafts/', view=post_drafts, name='post_drafts'),
    path(route='post/<int:pk>/', view=post_detail, name='post_detail'),
    path(route='post/new/', view=post_new, name='post_new'),
    path(route='post/<int:pk>/edit/', view=post_edit, name='post_edit'),
    path(route='post/<int:pk>/delete/', view=post_delete, name='post_delete'),
]

blog/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        verbose_name='Título',
        max_length=32,
    )
    text = models.TextField(
        verbose_name='Texto',
        max_length=1024,
        help_text='Campo limitado a 1024 caracteres.',
    )
    published = models.BooleanField(
        verbose_name='Publicar?',
        help_text='Se o campo estiver marcado o texto será publicado imediatamente.',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-updated_at']

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'published')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input'}),
            'text': forms.Textarea(
                attrs={
                    'class': 'textarea',
                },
            ),
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post


def index(request):
    posts = Post.objects.filter(published=True)[:5]
    return render(
        request=request,
        template_name='blog/index.html',
        context={'posts': posts},
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(
        request=request,
        template_name='blog/post-detail.html',
        context={'post': post},
    )

def post_drafts(request):
    posts = Post.objects.filter(published=False)
    return render(
        request=request,
        template_name='blog/post-drafts.html',
        context={'posts': posts},
    )


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(
        request=request,
        template_name='blog/post-new.html',
        context={'form': form},
    )


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(
        request=request,
        template_name='blog/post-edit.html',
        context={'form': form},
    )


@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect('blog:index')
    else:
        return render(
            request=request,
            template_name='blog/post-delete.html',
            context={'post': post},
        )

blog/templates/blog/index.html
{% extends 'base/base-bulma.html' %}
{% block title %}Ultimas postagens{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Ultimas postagens do blog" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Ultimas Postagens</h1>
        <h1 class="subtitle has-text-centered">Exibindo os 5 ultimos</h1>
        <div class="content">
            <p>Botão de criar post só irá aparecer se usuário estiver logado.</p>
            <p>Caso usuário tente acessar a url de criar post e outras ele será redirecionado para a página de login.</p>
            {% if user.is_authenticated %}
            <a class="button is-info" href="{% url 'blog:post_new' %}">Criar post</a>
            <a class="button" href="{% url 'blog:post_drafts' %}">Rascunhos</a>
            {% endif %}
        </div>
        {% for post in posts %}
        <div class="card">
            <div class="card-content">
                <p class="title">
                    <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
                </p>
                <p class="subtitle is-size-7">
                    Criado em: {{ post.created_at }} por
                    {{ post.author.first_name }}
                    {{ post.author.last_name }}
                </p>
                <div class="content">
                    <p>{{ post.text|truncatechars:200 }}</p>
                    <p class="is-size-7">Atualizado em: {{ post.updated_at }}</p>
                </div>
            </div>
        </div>
        <br>
        {% empty %}
        <p class="has-text-danger">Nenhum post disponível</p>
        {% endfor %}
    </div>
</section>
{% endblock content %}

blog/templates/blog/post-delete.html
{% extends 'base/base-bulma.html' %}
{% block title %}Deletar post{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Deletar post" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Tem certeza?</h1>
        <div class="content">
            <p>Você tem certeza que quer remover o post <b>{{ post.title }}</b>?</p>
            <p class="has-text-danger">🚨 Essa ação não poderá ser desfeita! 🚨</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="buttons">
                <button class="button is-danger">Sim, eu tenho certeza</button>
                <a class="button " href="{{ request.META.HTTP_REFERER }}">Não, me leve de volta</a>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

blog/templates/blog/post-detail.html
{% extends 'base/base-bulma.html' %}
{% block title %}Detalhes do post{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Detalhes do post" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <div class="content">
            {% if user.is_authenticated %}
            <a class="button is-info" href="{% url 'blog:post_edit' pk=post.pk %}">Editar post</a>
            {% endif %}
            <h1 class="title">{{ post.title }}</h1>
            {% if post.published_at %}
            <h2 class="subtitle  is-7">{{ post.published_at }}</h2>
            {% endif %}
            <p>{{ post.text }}</p>
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/blog/post-drafts.html
{% extends 'base/base-bulma.html' %}
{% block title %}Rascunhos{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Posts que ainda não foram publicados" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Posts que ainda não foram publicados</h1>
        {% for post in posts %}
        <div class="card">
            <div class="card-content">
                <p class="title">
                    <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
                </p>
                <p class="subtitle is-size-7">
                    Criado em: {{ post.created_at }} por
                    {{ post.author.first_name }}
                    {{ post.author.last_name }}
                </p>
                <div class="content">
                    <p>{{ post.text|truncatechars:200 }}</p>
                    <p class="is-size-7">Atualizado em: {{ post.updated_at }}</p>
                </div>
            </div>
        </div>
        <br>
        {% empty %}
        <p>Nenhum rascunho disponível</p>
        {% endfor %}
    </div>
</section>
{% endblock content %}

blog/templates/blog/post-edit.html
{% extends 'base/base-bulma.html' %}
{% block title %}Editar post{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Editar post" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Editar post</h1>
        <form method="post">
            {% include "base/snippets/form.html" %}
            <div class="buttons">
                <button class="button is-primary">Atualizar</button>
                <a class="button is-danger" href="{% url 'blog:post_delete' pk=form.instance.pk %}">Deletar</a>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

blog/templates/blog/post-new.html
{% extends 'base/base-bulma.html' %}
{% block title %}Novo post{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Novo post" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Novo post</h1>
        <form method="post">
            {% include "base/snippets/form.html" %}
            <div class="control">
                <button class="button is-primary">Publicar</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}