_mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    # Adicionando as urls `accounts` que o Django já tem prontas.
    # Templates pode ser modificados em `templates/registration`.
    path('accounts/', include('django.contrib.auth.urls')),
    # Rest
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Aplicativos.
    path('', include('home.urls')),
    path('axios/', include('axios.urls')),
    path('blog/', include('blog.urls')),
    path('gitignore/', include('gitignore.urls')),
    path('jquery/', include('jquery.urls')),
    path('jsfetch/', include('jsfetch.urls')),
    path('jsxmlhttprequest/', include('jsxmlhttprequest.urls')),
    path('leafletjs/', include('leafletjs.urls')),
    path('note/', include('note.urls')),
    path('poll/', include('poll.urls')),
    path('upload/', include('upload.urls')),
    # Configurando arquivos de media, não fazer isso em produção!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import index, post_detail, post_new, post_edit, post_delete, post_drafts

app_name = 'blog'
urlpatterns = [
    path(route='', view=index, name='index'),
    path(route='post/drafts/', view=post_drafts, name='post_drafts'),
    path(route='post/<int:pk>/', view=post_detail, name='post_detail'),
    path(route='post/new/', view=post_new, name='post_new'),
    path(route='post/<int:pk>/edit/', view=post_edit, name='post_edit'),
    path(route='post/<int:pk>/delete/', view=post_delete, name='post_delete'),
]

note/urls.py
from django.urls import path

from .views import NoteIndex, NoteCreate, NoteUpdate, NoteDelete

app_name = 'note'
urlpatterns = [
    path(route='', view=NoteIndex.as_view(), name='index'),
    path(route='new/', view=NoteCreate.as_view(), name='create'),
    path(route='<int:pk>/update/', view=NoteUpdate.as_view(), name='update'),
    path(route='<int:pk>/delete/', view=NoteDelete.as_view(), name='delete'),
]

note/models.py
from django.db import models


class Note(models.Model):
    title = models.CharField(
        verbose_name='Título',
        max_length=32,
    )
    text = models.TextField(
        verbose_name='Texto',
        max_length=1024,
        help_text='Campo limitado a 1024 caracteres.',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-updated_at']

note/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input'}),
            'text': forms.Textarea(
                attrs={
                    'class': 'textarea',
                },
            ),
        }

note/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import NoteForm
from .models import Note


class NoteIndex(ListView):
    template_name = 'note/index.html'
    context_object_name = 'notes'
    queryset = Note.objects.all().order_by('-updated_at')


class NoteCreate(CreateView):
    model = Note
    form_class = NoteForm
    template_name = 'note/create.html'
    success_url = reverse_lazy("note:index")


class NoteUpdate(UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'note/create.html'
    success_url = reverse_lazy("note:index")


class NoteDelete(DeleteView):
    model = Note
    template_name = 'base/snippets/confirm-delete.html'
    success_url = reverse_lazy("note:index")

note/templates/note/create.html
{% extends 'base/base-bulma.html' %}
{% block title %}Criar nota{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Criar nota" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Criar nota</h1>
        <form method="post">
            {% include "base/snippets/form.html" %}
            <div class="control">
                <button class="button is-primary">Criar</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

note/templates/note/edit.html
{% extends 'base/base-bulma.html' %}
{% block title %}Editar post{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Editar post" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Editar post</h1>
        <form method="post">
            {% include "base/snippets/form.html" %}
            <div class="buttons">
                <button class="button is-primary">Atualizar</button>
                <a class="button is-danger" href="{% url 'blog:post_delete' pk=form.instance.pk %}">Deletar</a>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

note/templates/note/index.html
{% extends 'base/base-bulma.html' %}
{% block title %}Notas{% endblock title %}
{% block seo %}
{{ block.super }}
<meta content="Notas" name="description">
{% endblock seo %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Notas</h1>
        <div class="content">
            <a class="button is-info is-outlined" href="{% url 'note:create' %}">Criar nota</a>
        </div>
        <div class="columns is-multiline is-mobile is-vcentered">
            {% for note in notes %}
            <div class="column is-4">
                <article
                        class="panel {% cycle 'is-primary' 'is-Llink' 'is-info' 'is-success' 'is-warning' 'is-danger'%}">
                    <p class="panel-heading">{{ note.title }}</p>
                    <div class="panel-block">
                        <p>{{ note.text }}</p>
                    </div>
                    <div class="panel-block has-text-centered">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-link is-outlined" href="{% url 'note:update' note.pk %}">
                                    Editar
                                </a>
                            </p>
                            <p class="control">
                                <a class="button is-danger is-outlined" href="{% url 'note:delete' note.pk %}">
                                    Deletar
                                </a>
                            </p>
                        </div>
                    </div>
                </article>
            </div>
            {% empty %}
            <div class="content">
                <p class="has-text-danger">Nenhuma nota criada ainda</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}